### ISSUE TITLE
Can this work realize the actual acceleration of xornet?

### ISSUE THREAD

**Issue by zhanghanqi** [akhauriyash/XNOR-convolution#2]
Can this work realize the actual acceleration of xornet?

**Comment by akhauriyash** [comment]
Hello,
Yes, I had demonstrated acceleration on a very toy use case. However, I had written this when I was very young (early in the field), and used it as a way to learn CUDA and C++. My apologies for keeping this as a public repo, but I would highly advise against using this code-base for any practical purposes.
